package constants

const (
	NATS_EVENT_NAME_BROADCAST    = "broadcast"
	NATS_EVENT_NAME_NOTIFICATION = "notification"
	NATS_SUBJECT_NAME_REALTIME   = "realtime-notification"

	NATS_EVENT_NAME_REWARDBACK_COMMISSION = "REWARD_BACK_COMMISSION"
	NATS_EVENT_NAME_CASHBACK_COMMISSION   = "CASH_BACK_COMMISSION"
	NATS_EVENT_NAME_REFERRAL_COMMISSION   = "REFERRAL_COMMISSION"
	NATS_EVENT_NAME_INDI_ALERT_REALTIME   = "indicator-alert"
	//VN_TIMEZONE = "Asia/Bangkok"

	EVENT_TYPE_SOCKET   = "SOCKET"
	EVENT_TYPE_TELEGRAM = "TELEGRAM"
)
